### ISSUE TITLE
competing trufflehog extension ?

### ISSUE THREAD

**Issue by commandline-be** [trufflesecurity/Trufflehog-Chrome-Extension#4]
https://chrome.google.com/webstore/search/trufflehog

is this the Trufflesecurity extension or did i just fool myself ?

**Comment by dxa4481** [comment]
That's it! It just got approved. I'll update the readme

**Comment by JLT032** [comment]
Thanks, please make it clear in the installation this is the trufflehogsecurity extension, now it lists "Offered by: dylan" which is somewhat confusing
